# --- Intranet: serve site root as-is ---
[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200
  force = true
  conditions = { Host = ["intranet.livingrealtykw.com"] }

# --- Events (public): everything on this host goes to events-public.html ---
[[redirects]]
  from = "/*"
  to = "/events-public.html"
  status = 200
  force = true
  conditions = { Host = ["events.livingrealtykw.com"] }

# --- Internal events: everything on this host goes to events-private.html ---
[[redirects]]
  from = "/*"
  to = "/events-private.html"
  status = 200
  force = true
  conditions = { Host = ["internalevents.livingrealtykw.com"] }

# (If you have a SPA catch-all like /* -> /index.html 200, keep it BELOW these rules or remove it.)
